# -*- coding: utf-8 -*-
"""Temperature Monitoring System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i3RUXGnHZkBmhVhHgDMXoM_0zXOWodzw
"""

import random
import time

def monitor_temperature():

    try:
        min_limit = float(input("Enter minimum temperature limit: "))
        max_limit = float(input("Enter maximum temperature limit: "))
    except ValueError:
        print("Invalid input. Please enter numerical values.")
        return

    print(f"\nMonitoring started. Range: {min_limit}°C - {max_limit}°C\n")


    while True:

        current_temp = round(random.uniform(10.0, 50.0), 2)


        if current_temp > max_limit:
            message = "!! HIGH TEMPERATURE ALERT !!"
        elif current_temp < min_limit:
            message = "!! LOW TEMPERATURE ALERT !!"
        else:
            message = "Temperature is Normal"

        print(f"[{time.strftime('%H:%M:%S')}] Temp: {current_temp}°C - {message}")


        time.sleep(2)

if __name__ == "__main__":
    monitor_temperature()